# Intro: Python and Pandas

This notebook will provide you with a short introduction into the basic command in Python, and specifically the basic commands of the pandas packages that we will be using in class. 
You should have completed already the [DataCamp Intro to Python for Data Science](https://www.datacamp.com/courses/intro-to-python-for-data-science) course. It is free and takes about four hours. If you havn't done that course please consider this a helpful ressource to familiarize yourself with Python/Pandas. 
After the class you will be able to read in data from a database and execute basic data manipulations using Pandas.

## Table of Contents
1. [General Remarks](#General-Remarks)
    1. [Python Setup](#Python-Setup)
    1. [Loading Data](#Load-the-Data)
1. [Data Analysis in Pandas](#Data-Analysis-in-Pandas)
    1. [Displaying Data](#Displaying-Data)
    1. [Subsetting Data](#Subsetting-Data)
    1. [Statistics](#Statistics)
    1. [Adding and Updating Data](#Adding-and-Updating-Data)
    1. [Grouping and Aggregating Data](#Grouping-and-Aggregating-Data)
    1. [Merging Dataframes](#Merging-Dataframes)
    1. [Saving a CSV](#Saving-a-CSV)

## General Remarks
---

Python: 
* Is a high-level interpreted general purpose programming language named after the Monty Python British comedy troupe
* Was created by Guido van Rossum, and is maintained by an open source community
* Is the fifth most popular programming language
* Is an object orientied language
* Is use mostly in data science because it is powerful and fast, and is compatible with other languages
* Runs everywhere, it's easy to learn, it's highly readable, open-source and its fast development time compared to other languages
* Comes with a growing and always-improving list of open-source libraries for scientific programming, data manipulation, and data analysis (e.g., Numpy, Scipy, Pandas, Scikit-Learn, Statsmodels, Matplotlib, Seaborn, PyTables, etc.)

IPython/Jupyter
* Is an enhanced, interactive python interpreter that started as a grad school project by Fernando Perez. 
* Evolved into the IPython notebook, which allowed users to archive their code, figures, and analysis in a single document, making doing reproducible research and sharing said research much easier. 
* Other languages including but not limited to Julia, Python and R were included. This then led to a rebranding known as the Jupyter Project.

### Python Setup

- In Python, we `import` packages. The `import` command allows us to use libraries created by others in our own work by "importing" them. You can think of importing a library as opening up a toolbox and pulling out a specific tool. 
- NumPy is short for numerical python. NumPy is a lynchpin in Python's scientific computing stack. Its strengths include a powerful *N*-dimensional array object, and a large suite of functions for doing numerical computing. 
- Pandas is a library in Python for data analysis that uses the DataFrame object from R which is similiar to a spreedsheet but allows you to do your analysis programaticaly rather than the point-and-click of Excel. It is a lynchpin of the PyData stack.  
- Psycopg2 or sqlalchemy are a python libraries for interfacing with a PostGreSQL database. 
- Matplotlib is the standard plotting library in python. 
`%matplotlib inline` is a so-called "magic" function of Jupyter that enables plots to be displayed inline with the code and text of a notebook.

#### This is how the start of a notebook might look like

In [48]:
# remember to put this line in your notebook, otherwise the visualization won't show up
%pylab inline
# import the packages
# numpy for array and matrix computation
import numpy as np

# pandas for data analysis
import pandas as pd

# matplotlib and seaborn are the data visualization packages
import matplotlib.pyplot as plt
import seaborn as sns

# sqlalchemy an psycopg2 are sql connection packages
from sqlalchemy import create_engine

# configure pandas display: set the maximum number of columns displayed to 25
pd.options.display.max_columns = 25

# use the __future__ version of division and print
from __future__ import division, print_function
import warnings
warnings.filterwarnings('ignore')

Populating the interactive namespace from numpy and matplotlib

In practice we typically load libraries like `numpy` and `pandas` with shortened aliases, e.g, `import numpy as np`. This is like saying, "`import numpy`, and wherever you see `np`, read it as `numpy`." Similarly, you'll often see `import pandas as pd`, or `import matplotlib.pyplot as plt`. 

Another shortcut is `%pylab inline`. This command includes both `import numpy as np` and `import matplotlib.pyplot as plt `. This shortcut was invented because it's faster to type `plt.plot()` rather than `matplotlib.pyplot.plot()`, and even programmers don't like to type more than they have to. 

In documentation and in examples, you will frequently see `numpy` commands starting with the alias `np` rather than `numpy` (e.g, `np.array()` or `np.argsort`) and `pandas` commands starting with `pd` (e.g., `pd.DataFrame()` or `pd.concat()`).

### Loading Data

Before we can start analysing the data we have to load it into memory. We can read in different kind of data formats. The Pandas package provides many ways to load data. It allows the user to read the data from a local csv or excel file, or pull the data from a relational database. Since we are working with the relational database ada_pub in this class, we will demonstrate how to use pandas to read data from a relational database. For examples to read data from a csv file, refert to the pandas documentation [Getting Data In/Out](pandas.pydata.org/pandas-docs/stable/10min.html#getting-data-in-out).

The function to create a sql query and put the data into a pandas dataframe (more to come) is `pd.read_sql()`. This function will ask for some information about the database, and what query you would like to run.

### Establish a connection to the ada_pub database
In the most simple case, only 2 parameters are required by the `pd.read_sql()` function to pull data. The first parameter is the connection to the database, the second parameter the actual SQL query. To create a connection we use the sqlalchemy package and tell it which database we want to connect to.

#### Parameter 1: connection

In [49]:
# create postgresql connection - three '/' indicate to use default host, port, username, and password
engine = create_engine('postgresql:///ada_pub')

#### Parameter 2: query
Depending on what data we are interested in, we can use different queries to pull different data. In this example, we will pull all the content of the table projects that we can find for agency USDA in year 2014. The three quotation marks surrounding the query body is called multi-line string. It is quite handy for writing sql queries because the new line character will be considered part of the string, instead of breaking the string

In [50]:
QUERY = '''
SELECT *
FROM projects
WHERE department = 'USDA' AND fy = '2014';
'''

### Pull data from the database
Now that we know what the arguments are for the query, we can pass them to the `pd.read_sql()` function, and obtain the data.

In [51]:
# here we pass the query and the connection to the pd.read_sql() function 
example=pd.read_sql_query(QUERY,con=engine)

In [52]:
example

,project_id,project_terms,project_title,department,agency,ic_center,project_number,project_start_date,project_end_date,contact_pi_project_leader,other_pis,congressional_district,duns_number,organization_name,organization_city,organization_state,organization_zip,organization_country,budget_start_date,budget_end_date,cfda_code,fy,fy_total_cost,fy_total_cost_sub_projects
0,589214,Bees; Chemicals; Development; Devices; Diet; ...,IMPROVE NUTRITION FOR HONEY BEE COLONIES TO ST...,USDA,ARS,None,ARS-0425868,10/1/2013,2/6/2014,"HOFFMAN, GLORIA D",None,2.0,078274365,HONEY BEE RESEARCH INSTITUTE AND NATURE CENTER...,TUCSON,AZ,85719,UNITED STATES,None,None,10.001,2014,NaN,None
1,589224,Affect; Algae; Amendment; Appearance; base; B...,ALGAL-BASED WATER TREATMENT TECHNOLOGIES FOR S...,USDA,ARS,None,ARS-0426136,1/1/2014,12/31/2018,"HALL, DAVID GOODSELL",None,0.0,None,SUBTROPICAL INSECTS AND HORTICULTURE RESEARCH,FORT PIERCE,FL,34945,UNITED STATES,None,None,10.001,2014,NaN,None
2,591601,Area; base; Biological; California; Consumpti...,BIOLOGICAL CONTROL OF PIERCE'S DISEASE OF GRAP...,USDA,NIFA,None,0212205,8/20/2014,9/30/2014,"HOPKINS, DO, .",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
3,593659,absorption; Address; Anemia; Anemia due to Ch...,MOLECULAR MECHSNISMS OF INTESTINAL METAL ION T...,USDA,NIFA,None,0217191,7/8/2014,7/9/2014,"COLLINS, JA, F..",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
4,597171,Climate; Decision Support Systems; Developmen...,ASSESSING CLIMATE INFORMATION NEEDS AND OPPORT...,USDA,NIFA,None,0226918,8/19/2014,8/20/2014,"JONES, J.",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.202,2014,NaN,None
5,599511,Attention; base; Development; Fisheries; Fish...,DEVELOPMENT OF TOOLS TO ENABLE PLACE-BASED MAN...,USDA,NIFA,None,0233896,5/30/2014,9/30/2018,"STRUVE, JU, .",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
6,689200,Agriculture; Farming environment; New York; N...,NITROGEN LOSSES FROM AGRICULTURE: COMPARING OR...,USDA,NIFA,None,1000965,10/1/2013,9/30/2016,"HOWARTH, RO.","MARINO, RO, M",NaN,613809599,CORNELL UNIVERSITY INC,ORISKANY,NY,13424-3921,UNITED STATES,None,None,10.203,2014,NaN,None
7,690030,Animals; Embryo; Genome; programs; Research; ...,NATIONAL ANIMAL GENOME RESEARCH PROGRAM,USDA,NIFA,None,1002276,1/6/2014,9/30/2018,"BRUEMMER, J.",None,NaN,149546160,COLORADO STATE UNIVERSITY,DENVER,CO,80203-1148,UNITED STATES,None,None,10.203,2014,NaN,None
8,690062,Population; Population Growth; Process; Repro...,"DYNAMICS, PERSISTENCE AND MANAGEMENT OF VERTEB...",USDA,NIFA,None,1002321,1/28/2014,12/23/2018,"OLI, M.","OLI, MA, K",NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
9,689214,Development; Growth; Lead; Nematoda; next gen...,ANALYSIS OF SEXUAL REPRODUCTION IN A ROOT-KNOT...,USDA,NIFA,None,1001006,1/6/2014,9/30/2018,"ENGEBRECHT, J.","BRITT, AN,",NaN,047120084,UNIVERSITY OF CALIFORNIA DAVIS,DAVIS,CA,95618-6153,UNITED STATES,None,None,10.203,2014,NaN,None
10,689388,Agriculture; Cost Sharing; Data; economic imp...,ECONOMIC IMPACT OF VALUE-ADDED AGRICULTURE IN ...,USDA,NIFA,None,1001368,10/1/2013,9/30/2018,"BROWN, A.",None,NaN,042092122,NORTH CAROLINA STATE UNIVERSITY RALEIGH,RALEIGH,NC,27695-0001,UNITED STATES,None,None,10.203,2014,NaN,None
11,690284,Biological; Nematoda; Plants; Production; Res...,"VARIABILITY, ADAPTATION, AND MANAGEMENT OF NEM...",USDA,NIFA,None,1002704,3/7/2014,9/30/2018,"LAWRENCE, K, .",None,NaN,066470972,AUBURN UNIVERSITY AT AUBURN,AUBURN,AL,36849-0001,UNITED STATES,None,None,10.203,2014,NaN,None
12,689215,base; Bird Diseases; design; Diet; Genetic; G...,GENETIC BASES FOR RESISTANCE AND IMMUNITY TO A...,USDA,NIFA,None,1001007,10/1/2013,9/30/2018,"KLASING, K.",None,NaN,047120084,UNIVERSITY OF CALIFORNIA DAVIS,DAVIS,CA,95618-6153,UNITED STATES,None,None,10.203,2014,NaN,None
13,689424,Agriculture; Bees; Eating; Genes; Genetic; Gr...,MECHANISMS AND GENETICS OF REPRODUCTION IN INS...,USDA,NIFA,None,1001426,10/1/2013,9/30/2018,"MARSHALL, J.",None,NaN,929773554,KANSAS STATE UNIVERSITY,MANHATTAN,KS,66506-1109,UNITED STATES,None,None,10.203,2014,NaN,None
14,689425,Agriculture; Biotechnology; Economics; farmer...,ECONOMICS OF CROP BIOTECHNOLOGIES,USDA,NIFA,None,1001427,10/1/2013,9/30/2015,"MARRA, M.",None,NaN,042092122,NORTH CAROLINA STATE UNIVERSITY RALEIGH,RALEIGH,NC,27695-0001,UNITED STATES,None,None,10.203,2014,NaN,None
15,689742,beef; Carbon; Cattle; cost; feeding; Growth; ...,THE EFFECT OF OPTIMASE AND RUMENSIN ON BEEF CA...,USDA,NIFA,None,1001905,11/7/2013,9/30/2018,"LALMAN, D.","HORN, GE, ; RICHARDS, CH,",NaN,049987720,OKLAHOMA STATE UNIVERSITY STILLWATER,STILLWATER,OK,74078-1030,UNITED STATES,None,None,10.203,2014,NaN,None
16,687126,Agriculture; Alleles; Amendment; American; Bi...,HATCH ACT OF 1887 - NY,USDA,NIFA,None,2014-31100-03619,6/15/2013,2/14/2014,"BURR, THOMAS J.",None,23.0,872612445,CORNELL UNIVERSITY ITHACA,ITHACA,NY,14850-2820,UNITED STATES,None,None,10.212,2014,490142.0,None
17,687674,bagasse; Ethanol; experience; forest; Laborat...,ANIMAL HEALTH AND DISEASE RESEARCH PROGRAM - OH,USDA,NIFA,None,2014-36100-06039,1/1/2013,12/31/2013,"SLACK, STEVEN A.",None,16.0,171605848,OHIO STATE UNIVERSITY,WOOSTER,OH,44691-0000,UNITED STATES,None,None,10.31,2014,56954.0,None
18,687127,Agriculture; Alleles; Amendment; American; Bi...,HATCH ACT OF 1887 (MULTISTATE RESEARCH FUND) - NY,USDA,NIFA,None,2014-31200-03619,7/1/2013,2/28/2014,"BURR, THOMAS J.",None,23.0,872612445,CORNELL UNIVERSITY ITHACA,ITHACA,NY,14850-2820,UNITED STATES,None,None,10.212,2014,765728.0,None
19,688523,Agriculture; Arthritis; disability; Facial In...,AGRABILITY OF UTAH,USDA,NIFA,None,2014-41590-22321,2/15/2014,2/14/2016,"MILLER, RHONDA","PATE, MICHAEL; JOHNSON, TRACY",1.0,072983455,UTAH STATE UNIVERSITY,LOGAN,UT,84322-0000,UNITED STATES,None,None,10.31,2014,180000.0,None
20,688604,Buffaloes; Economics; Education Projects; Foo...,SGU RESTORING THE BUFFALO ECONOMY EDUCATION PR...,USDA,NIFA,None,2014-38421-21997,3/1/2014,2/28/2017,"BORDEAUX, SHAWN","REDOWL-NEISS, SHERRY D",0.0,072918485,SINTE GLESKA UNIVERSITY,MISSION,SD,57555-0000,UNITED STATES,None,None,10.31,2014,107468.0,None
21,688692,American Indians; Arts; Biological Preservati...,MCINTIRE-STENNIS COOPERATIVE FORESTRY RESEARCH...,USDA,NIFA,None,2014-32100-06058,9/1/2014,8/31/2015,"ZIMMERMAN, THOMAS",None,0.0,090003765,UNIVERSITY OF THE VIRGIN ISLANDS,ST THOMAS,VI,8029990,UNITED STATES,None,None,10.33,2014,44900.0,None
22,688866,Accounting; Bees; Cranberries; Environment; H...,NATIVE BEES IN CRANBERRY AGROECOSYSTEMS: WHERE...,USDA,NIFA,None,0232505,10/1/2013,9/30/2017,"GRATTON, C.",None,NaN,161202122,UNIVERSITY OF WISCONSIN MADISON,MADISON,WI,53706-1415,UNITED STATES,None,None,10.203,2014,NaN,None
23,690385,Agriculture; antimicrobial; Bacteria; Growth;...,ARE DIACYL RESORCINOLS THE UNKNOWN ANTIMICROBI...,USDA,NIFA,None,1002866,7/1/2014,6/30/2016,"ANDERSON, A.",None,NaN,072983455,UTAH STATE UNIVERSITY,LOGAN,UT,84322-0001,UNITED STATES,None,None,10.203,2014,NaN,None
24,689804,cost; Esthetics; feeding; Goals; improved; In...,REFINING INSECT PEST MANAGEMENT FOR THE LOUISI...,USDA,NIFA,None,1001982,1/22/2014,11/10/2017,"BEUZELIN, J.",None,NaN,042123745,LOUISIANA STATE UNIVERSITY SHREVEPORT,SHREVEPORT,LA,71115-2301,UNITED STATES,None,None,10.203,2014,NaN,None
25,690768,Air; Businesses; cost; Fossil Fuels; Guidelin...,RESOURCE MANAGEMENT IN COMMERCIAL GREENHOUSE P...,USDA,NIFA,None,1004331,9/23/2014,9/30/2017,"KRUG, B, .",None,NaN,111089470,UNIVERSITY SYSTEM OF NEW HAMPSHIRE,LEE,NH,03861-6659,UNITED STATES,None,None,10.203,2014,NaN,None
26,689868,Agriculture; Carbon; design; Development; Eco...,GREEN ROOF DESIGN AND MANAGEMENT PRACTICES TO ...,USDA,NIFA,None,1002073,1/10/2014,12/31/2018,"ROWE, D.","ANDRESEN, JE, ; CAMPA, HE, ; WESTPHAL, JO,",NaN,193247145,MICHIGAN STATE UNIVERSITY,EAST LANSING,MI,48824-1046,UNITED STATES,None,None,10.203,2014,NaN,None
27,689928,Agriculture; Apidae; Apis; Bees; Disease; Ens...,IDENTIFYING FACTORS THAT REDUCE THE REPRODUCTI...,USDA,NIFA,None,1002141,12/9/2013,9/30/2018,"TARPY, D.",None,NaN,042092122,NORTH CAROLINA STATE UNIVERSITY RALEIGH,RALEIGH,NC,27695-0001,UNITED STATES,None,None,10.203,2014,NaN,None
28,689929,base; Domestic Fowls; genetic technology; Gen...,ADVANCED TECHNOLOGIES FOR THE GENETIC IMPROVEM...,USDA,NIFA,None,1002142,1/3/2014,9/30/2018,"FROMAN, DA, PA.",None,NaN,053599908,OREGON STATE UNIVERSITY,CORVALLIS,OR,97331,UNITED STATES,None,None,10.203,2014,NaN,None
29,690448,Agriculture; Back; Businesses; Categories; De...,FLAVOR DEVELOPMENT IN DISTILLED SPIRITS,USDA,NIFA,None,1002972,8/8/2014,7/31/2019,"BERGLUND, K.",None,NaN,193247145,MICHIGAN STATE UNIVERSITY,EAST LANSING,MI,48824-1046,UNITED STATES,None,None,10.203,2014,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3162,813592,absorption; Agriculture; Anatomy; Animal Mode...,"BIOAVAILABILITY OF IRON, ZINC AND SELECT PHYTO...",USDA,ARS,None,ARS-0426380,1/29/2014,1/28/2019,"GLAHN, RAYMOND P",None,23.0,None,AGRICULTURAL RESEARCH SERVICE,ITHACA,NY,14853,UNITED STATES,None,None,10.001,2014,962419.0,None
3163,813594,Affect; Animal Experimentation; Animals; base...,GENETIC AND GENOMIC APPROACHES TO IMPROVE SWIN...,USDA,ARS,None,ARS-0426415,6/1/2014,2/28/2018,"ROHRER, GARY A",None,3.0,None,AGRICULTURAL RESEARCH SERVICE,CLAY CENTER,NE,68933,UNITED STATES,None,None,10.001,2014,1279060.0,None
3164,813595,Acids; Alcohols; Anabolism; Arabidopsis; base...,IMPROVEMENT OF POSTHARVEST PERFORMANCE OF ORNA...,USDA,ARS,None,ARS-0426439,12/15/2013,12/14/2018,"JIANG, CAI ZHONG",None,4.0,None,AGRICULTURAL RESEARCH SERVICE,DAVIS,CA,95616,UNITED STATES,None,None,10.001,2014,260371.0,None
3165,813604,Address; Affect; Animal Diseases; Animals; ar...,PREDICTIVE BIOLOGY OF EMERGING VECTOR-BORNE VI...,USDA,ARS,None,ARS-0426512,4/17/2014,4/30/2017,"MCVEY, DAVID SCOTT",None,1.0,None,AGRICULTURAL RESEARCH SERVICE,MANHATTAN,KS,66506,UNITED STATES,None,None,10.001,2014,895500.0,None
3166,813598,Address; Adipose tissue; Adult; Affect; Age; ...,IMPACT OF EARLY DIETARY FACTORS ON CHILD DEVEL...,USDA,ARS,None,ARS-0426492,3/23/2014,3/22/2019,"BRENNAN, DEBORAH L",None,2.0,None,AGRICULTURAL RESEARCH SERVICE,LITTLE ROCK,AR,72204,UNITED STATES,None,None,10.001,2014,7759400.0,None
3167,813599,18 year old; age group; American; arm; base; ...,IMPROVING NUTRITION AND PHYSICAL ACTIVITY RELA...,USDA,ARS,None,ARS-0426493,5/1/2014,4/30/2019,"THOMSON, JESSICA L",None,2.0,136617730,AGRICULTURAL RESEARCH SERVICE,STONEVILLE,MS,38776,UNITED STATES,None,None,10.001,2014,428981.0,None
3168,813600,Adolescent; Androgens; Animal Model; Animals;...,REGULATORY MECHANISMS INDUCED BY HEALTH-PROMOT...,USDA,ARS,None,ARS-0426494,4/2/2014,4/1/2019,"WANG, THOMAS TY",None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,1134740.0,None
3169,813602,Adipose tissue; Anti-inflammatory; Anti-Infla...,DIETARY REGULATION OF IMMUNITY AND INFLAMMATION,USDA,ARS,None,ARS-0426497,3/28/2014,3/27/2019,"DAWSON, HARRY D",None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,1384270.0,None
3170,813603,Acids; adiponectin; Adult; Adverse effects; A...,HEALTH PROMOTING ROLES OF FOOD BIO-ACTIVE PHEN...,USDA,ARS,None,ARS-0426502,3/16/2014,3/15/2019,"PARK, JAE B",None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,1074021.0,None
3171,813606,Agriculture; Americas; Arts; base; beef; Bras...,USDA NATIONAL NUTRIENT DATABANK FOR FOOD COMPO...,USDA,ARS,None,ARS-0426560,2/20/2014,2/19/2019,None,None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,3705775.0,None
3172,813612,Affect; Amylases; Beets; Collaborations; Colo...,DEVELOPING TECHNOLOGIES THAT ENABLE GROWTH AND...,USDA,ARS,None,ARS-0426599,9/22/2014,9/21/2019,"EGGLESTON, GILLIAN",None,1.0,None,AGRICULTURAL RESEARCH SERVICE,NEW ORLEANS,LA,70124-4305,UNITED STATES,None,None,10.001,2014,2263140.0,None
3173,813613,Acculturation; Adipose tissue; adjudicate; An...,CARDIOVASCULAR NUTRITION AND HEALTH,USDA,ARS,None,ARS-0426624,4/17/2014,4/16/2019,"SWIETLIK, DARIUSZ M",None,7.0,None,AGRICULTURAL RESEARCH SERVICE,BOSTON,MA,02111,UNITED STATES,None,None,10.001,2014,1320812.0,None
3174,813614,Affect; Age related macular degeneration; Agi...,"VISION, AGING, AND NUTRITION",USDA,ARS,None,ARS-0426629,5/1/2014,4/30/2019,"SWIETLIK, DARIUSZ M",None,7.0,None,AGRICULTURAL RESEARCH SERVICE,BOSTON,MA,02111,UNITED STATES,None,None,10.001,2014,867215.0,None
3175,813615,Adipose tissue; Adult; Affect; Amino Acids; A...,NOVEL FUNCTIONS AND BIOMARKERS FOR VITAMINS AN...,USDA,ARS,None,ARS-0426640,1/29/2014,1/28/2019,"HUANG, LIPING",None,4.0,None,AGRICULTURAL RESEARCH SERVICE,DAVIS,CA,95616,UNITED STATES,None,None,10.001,2014,473684.0,None
3176,813617,Adult; Adult Children; Agriculture; Antacids;...,USDA DIETARY SUPPLEMENT INGREDIENT DATABASE,USDA,ARS,None,ARS-0426694,2/20/2014,2/19/2019,"PEHRSSON, PAMELA R",None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,158548.0,None
3177,813618,Affect; Agar; Anastomosis - action; base; Bas...,DETECTION AND IDENTIFICATION OF SOIL-BORNE PLA...,USDA,ARS,None,ARS-0426725,4/29/2014,8/31/2017,"LAKSHMAN, DILIP K",None,0.0,None,AGRICULTURAL RESEARCH SERVICE,WASHINGTON,DC,20002,UNITED STATES,None,None,10.001,2014,219371.0,None
3178,813620,Age; Age-Years; Aging; Assessment tool; Body ...,RURAL AGING STUDY,USDA,ARS,None,ARS-0426746,5/1/2014,4/30/2019,"SWIETLIK, DARIUSZ M",None,7.0,None,AGRICULTURAL RESEARCH SERVICE,BOSTON,MA,02111,UNITED STATES,None,None,10.001,2014,167130.0,None
3179,813622,Adherence; Adult; Affect; Age; American; Amer...,ASSESSING THE IMPACT OF DIET ON INFLAMMATION I...,USDA,ARS,None,ARS-0426782,1/18/2014,1/17/2019,"STEPHENSEN, CHARLES B",None,4.0,None,AGRICULTURAL RESEARCH SERVICE,DAVIS,CA,95616,UNITED STATES,None,None,10.001,2014,2714120.0,None
3180,813623,American; Ants; Architecture; Area; Argentine...,INVASIVE ANT BIOLOGY AND CONTROL,USDA,ARS,None,ARS-0426807,9/8/2014,9/7/2019,"VALLES, STEVEN M",None,2.0,None,AGRICULTURAL RESEARCH SERVICE,GAINESVILLE,FL,32608,UNITED STATES,None,None,10.001,2014,2169831.0,None
3181,813624,acylcarnitine; Adipose tissue; American; Amer...,IMPROVING PUBLIC HEALTH BY UNDERSTANDING DIVER...,USDA,ARS,None,ARS-0426826,3/16/2014,3/15/2019,"BENNETT, BRIAN JOSEPH",None,4.0,None,AGRICULTURAL RESEARCH SERVICE,DAVIS,CA,95616,UNITED STATES,None,None,10.001,2014,3081852.0,None
3182,813626,Barley; Communication; Data; Databases; Devel...,FUSARIUM HEAD BLIGHT OF WHEAT AND BARLEY,USDA,ARS,None,ARS-0426886,5/27/2014,5/26/2019,"COSTA, JOSE",None,5.0,136617730,AGRICULTURAL RESEARCH SERVICE,BELTSVILLE,MD,20705,UNITED STATES,None,None,10.001,2014,NaN,None
3183,813628,Animals; Birth; Development; Diet; Disease; D...,REDUCING ANIMAL STRESS AND THE INCIDENCE OR PR...,USDA,ARS,None,ARS-0427098,7/1/2014,9/30/2017,"EICHER, SUSAN D",None,4.0,None,AGRICULTURAL RESEARCH SERVICE,WEST LAFAYETTE,IN,47907,UNITED STATES,None,None,10.001,2014,487483.0,None
3184,813629,Affect; Animals; Antigens; base; Bioinformati...,GENOMICS OF LIVESTOCK PESTS,USDA,ARS,None,ARS-0427176,6/1/2014,5/31/2019,"GUERRERO, FELICITO",None,21.0,None,AGRICULTURAL RESEARCH SERVICE,KERRVILLE,TX,78029,UNITED STATES,None,None,10.001,2014,2037751.0,None
3185,813633,Agriculture; Aircraft; analytical method; Are...,APPLICATION TECHNOLOGIES TO IMPROVE THE EFFECT...,USDA,ARS,None,ARS-0427340,8/4/2014,4/30/2019,"HUANG, YANBO",None,2.0,136617730,AGRICULTURAL RESEARCH SERVICE,STONEVILLE,MS,38776,UNITED STATES,None,None,10.001,2014,1144645.0,None
3186,813634,Applied Research; cost; Development; Droughts...,"DEVELOPMENT OF PRODUCTIVE, PROFITABLE, AND SUS...",USDA,ARS,None,ARS-0427342,4/1/2014,3/31/2019,"REDDY, KRISHNA NARASIM",None,2.0,136617730,AGRICULTURAL RESEARCH SERVICE,STONEVILLE,MS,38776,UNITED STATES,None,None,10.001,2014,1378672.0,None
3187,813637,Acids; Affect; Aldehydes; Beta-glucuronidase;...,TECHNOLOGIES FOR IMPROVING PROCESS EFFICIENCIE...,USDA,ARS,None,ARS-0427437,8/9/2014,8/8/2019,"DIEN, BRUCE S",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1345714.0,None
3188,813638,base; Biochemical; Biomass; Collaborations; E...,BIOCHEMICAL TECHNOLOGIES TO ENABLE THE COMMERC...,USDA,ARS,None,ARS-0427438,8/21/2014,8/20/2019,"SLININGER, PATRICIA J WATSON",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,833060.0,None
3189,813639,Acids; Arabinose; Aspergillus; Butanols; carb...,DEVELOP TECHNOLOGIES FOR PRODUCTION OF PLATFOR...,USDA,ARS,None,ARS-0427439,8/29/2014,8/28/2019,"SAHA, BADAL C",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1281630.0,None
3190,813643,Agriculture; antimicrobial; Antioxidants; bas...,"ENABLE NEW MARKETABLE, VALUE-ADDED COPRODUCTS ...",USDA,ARS,None,ARS-0427684,9/8/2014,9/7/2019,"MOREAU, ROBERT A",None,13.0,None,AGRICULTURAL RESEARCH SERVICE,WYNDMOOR,PA,19038,UNITED STATES,None,None,10.001,2014,2133178.0,None
3191,813655,Agriculture; Anti-Bacterial Agents; Bacteria;...,NEW BIOBASED PRODUCTS AND IMPROVED BIOCHEMICAL...,USDA,ARS,None,ARS-0427980,9/19/2014,9/18/2019,"BISCHOFF, KENNETH M",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1547666.0,None

By now we have finished loading the data, and we are ready to do some data analysis

## Data Analysis in Pandas

When we are working with Pandas we are thinking in terms of dataframes. It's a pandas representation of a spreadsheet/ sql table/Stata/R or SAS dataset. It contains information such as column names, row indices (starting from 0), and the actual data. They are the basic objects on which we will perform our data analysis.

### Displaying Data

#### The shape of the dataframe
When we get the data, we usually want to know how many rows and columns are there in the data. We can find out the row and column numbers by calling the shape instance variable with a dot operator.

In [53]:
# shape of a dataframe (row number, column number)
example.shape
# We can see that the dataframe contains 3192 rows, and 24 columns

(3192, 24)

In [47]:
# See the list of variables in data
example.count()

project_id                    3192
project_terms                 3192
project_title                 3192
department                    3192
agency                        3192
ic_center                        0
project_number                3192
project_start_date            3192
project_end_date              3192
contact_pi_project_leader     3180
other_pis                     1072
congressional_district        1360
duns_number                   2894
organization_name             3189
organization_city             3189
organization_state            3189
organization_zip              3087
organization_country          3192
budget_start_date                0
budget_end_date                  0
cfda_code                     3192
fy                            3192
fy_total_cost                 1005
fy_total_cost_sub_projects       0
dtype: int64

#### The head and tail of the dataframe
It is also helpful to have a look at the first or last few rows of the data for a first impression, as well as a sanity check. We can call the head()/tail() methods. We can also specify how many lines we would like to see in the parentheses at the end. We choose to display 10. If not specified, by default the first 5 lines will be returned

In [6]:
# display the first few rows of the dataframe
example.head(10)

,project_id,project_terms,project_title,department,agency,ic_center,project_number,project_start_date,project_end_date,contact_pi_project_leader,other_pis,congressional_district,duns_number,organization_name,organization_city,organization_state,organization_zip,organization_country,budget_start_date,budget_end_date,cfda_code,fy,fy_total_cost,fy_total_cost_sub_projects
0,589214,Bees; Chemicals; Development; Devices; Diet; ...,IMPROVE NUTRITION FOR HONEY BEE COLONIES TO ST...,USDA,ARS,None,ARS-0425868,10/1/2013,2/6/2014,"HOFFMAN, GLORIA D",None,2.0,078274365,HONEY BEE RESEARCH INSTITUTE AND NATURE CENTER...,TUCSON,AZ,85719,UNITED STATES,None,None,10.001,2014,NaN,None
1,589224,Affect; Algae; Amendment; Appearance; base; B...,ALGAL-BASED WATER TREATMENT TECHNOLOGIES FOR S...,USDA,ARS,None,ARS-0426136,1/1/2014,12/31/2018,"HALL, DAVID GOODSELL",None,0.0,None,SUBTROPICAL INSECTS AND HORTICULTURE RESEARCH,FORT PIERCE,FL,34945,UNITED STATES,None,None,10.001,2014,NaN,None
2,591601,Area; base; Biological; California; Consumpti...,BIOLOGICAL CONTROL OF PIERCE'S DISEASE OF GRAP...,USDA,NIFA,None,0212205,8/20/2014,9/30/2014,"HOPKINS, DO, .",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
3,593659,absorption; Address; Anemia; Anemia due to Ch...,MOLECULAR MECHSNISMS OF INTESTINAL METAL ION T...,USDA,NIFA,None,0217191,7/8/2014,7/9/2014,"COLLINS, JA, F..",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
4,597171,Climate; Decision Support Systems; Developmen...,ASSESSING CLIMATE INFORMATION NEEDS AND OPPORT...,USDA,NIFA,None,0226918,8/19/2014,8/20/2014,"JONES, J.",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.202,2014,NaN,None
5,599511,Attention; base; Development; Fisheries; Fish...,DEVELOPMENT OF TOOLS TO ENABLE PLACE-BASED MAN...,USDA,NIFA,None,0233896,5/30/2014,9/30/2018,"STRUVE, JU, .",None,NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
6,689200,Agriculture; Farming environment; New York; N...,NITROGEN LOSSES FROM AGRICULTURE: COMPARING OR...,USDA,NIFA,None,1000965,10/1/2013,9/30/2016,"HOWARTH, RO.","MARINO, RO, M",NaN,613809599,CORNELL UNIVERSITY INC,ORISKANY,NY,13424-3921,UNITED STATES,None,None,10.203,2014,NaN,None
7,690030,Animals; Embryo; Genome; programs; Research; ...,NATIONAL ANIMAL GENOME RESEARCH PROGRAM,USDA,NIFA,None,1002276,1/6/2014,9/30/2018,"BRUEMMER, J.",None,NaN,149546160,COLORADO STATE UNIVERSITY,DENVER,CO,80203-1148,UNITED STATES,None,None,10.203,2014,NaN,None
8,690062,Population; Population Growth; Process; Repro...,"DYNAMICS, PERSISTENCE AND MANAGEMENT OF VERTEB...",USDA,NIFA,None,1002321,1/28/2014,12/23/2018,"OLI, M.","OLI, MA, K",NaN,002236250,UNIVERSITY OF FLORIDA,GAINESVILLE,FL,32611-0110,UNITED STATES,None,None,10.203,2014,NaN,None
9,689214,Development; Growth; Lead; Nematoda; next gen...,ANALYSIS OF SEXUAL REPRODUCTION IN A ROOT-KNOT...,USDA,NIFA,None,1001006,1/6/2014,9/30/2018,"ENGEBRECHT, J.","BRITT, AN,",NaN,047120084,UNIVERSITY OF CALIFORNIA DAVIS,DAVIS,CA,95618-6153,UNITED STATES,None,None,10.203,2014,NaN,None

In [7]:
# last few rows of the dataframe
# the syntax is similar to head
example.tail()

,project_id,project_terms,project_title,department,agency,ic_center,project_number,project_start_date,project_end_date,contact_pi_project_leader,other_pis,congressional_district,duns_number,organization_name,organization_city,organization_state,organization_zip,organization_country,budget_start_date,budget_end_date,cfda_code,fy,fy_total_cost,fy_total_cost_sub_projects
3187,813637,Acids; Affect; Aldehydes; Beta-glucuronidase;...,TECHNOLOGIES FOR IMPROVING PROCESS EFFICIENCIE...,USDA,ARS,None,ARS-0427437,8/9/2014,8/8/2019,"DIEN, BRUCE S",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1345714.0,None
3188,813638,base; Biochemical; Biomass; Collaborations; E...,BIOCHEMICAL TECHNOLOGIES TO ENABLE THE COMMERC...,USDA,ARS,None,ARS-0427438,8/21/2014,8/20/2019,"SLININGER, PATRICIA J WATSON",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,833060.0,None
3189,813639,Acids; Arabinose; Aspergillus; Butanols; carb...,DEVELOP TECHNOLOGIES FOR PRODUCTION OF PLATFOR...,USDA,ARS,None,ARS-0427439,8/29/2014,8/28/2019,"SAHA, BADAL C",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1281630.0,None
3190,813643,Agriculture; antimicrobial; Antioxidants; bas...,"ENABLE NEW MARKETABLE, VALUE-ADDED COPRODUCTS ...",USDA,ARS,None,ARS-0427684,9/8/2014,9/7/2019,"MOREAU, ROBERT A",None,13.0,None,AGRICULTURAL RESEARCH SERVICE,WYNDMOOR,PA,19038,UNITED STATES,None,None,10.001,2014,2133178.0,None
3191,813655,Agriculture; Anti-Bacterial Agents; Bacteria;...,NEW BIOBASED PRODUCTS AND IMPROVED BIOCHEMICAL...,USDA,ARS,None,ARS-0427980,9/19/2014,9/18/2019,"BISCHOFF, KENNETH M",None,18.0,064539612,U.S. AGRICULTURAL RESEARCH SERVICE,PEORIA,IL,61604,UNITED STATES,None,None,10.001,2014,1547666.0,None

### Columns, rows, data selection

#### Column names
to see which columns are there in the data, use the following syntax.

In [8]:
example.columns

Index([u'project_id', u'project_terms', u'project_title', u'department',
       u'agency', u'ic_center', u'project_number', u'project_start_date',
       u'project_end_date', u'contact_pi_project_leader', u'other_pis',
       u'congressional_district', u'duns_number', u'organization_name',
       u'organization_city', u'organization_state', u'organization_zip',
       u'organization_country', u'budget_start_date', u'budget_end_date',
       u'cfda_code', u'fy', u'fy_total_cost', u'fy_total_cost_sub_projects'],
      dtype='object')

#### Single column selection
If we want to select a specific column, we can use the following syntax:

In [9]:
# select a single column: the dataframe variable name, followed by square brackets, and then put the
# the column name between quotes (either single or double). 
example['agency'].head()

0     ARS
1     ARS
2    NIFA
3    NIFA
4    NIFA
Name: agency, dtype: object

In [10]:
# the same would be
example.agency.head()

0     ARS
1     ARS
2    NIFA
3    NIFA
4    NIFA
Name: agency, dtype: object

#### Multiple-column selection
to select multiple columns, wrap the column names in a python list, then put the list or tuple between the brackets after the dataframe

In [11]:
# here we selected the columns and assigned them to a new dataframe example2
example2 = example[['agency', 'project_title', 'fy_total_cost',
                           'project_start_date','project_end_date']]
example2.head()

,agency,project_title,fy_total_cost,project_start_date,project_end_date
0,ARS,IMPROVE NUTRITION FOR HONEY BEE COLONIES TO ST...,NaN,10/1/2013,2/6/2014
1,ARS,ALGAL-BASED WATER TREATMENT TECHNOLOGIES FOR S...,NaN,1/1/2014,12/31/2018
2,NIFA,BIOLOGICAL CONTROL OF PIERCE'S DISEASE OF GRAP...,NaN,8/20/2014,9/30/2014
3,NIFA,MOLECULAR MECHSNISMS OF INTESTINAL METAL ION T...,NaN,7/8/2014,7/9/2014
4,NIFA,ASSESSING CLIMATE INFORMATION NEEDS AND OPPORT...,NaN,8/19/2014,8/20/2014

#### single/ multiple cell(s) selection
Use the `loc` method for cell selection. Pass the row and column indices in the _square brackets_ after `loc`. Specify the row index first, and then column name, separated by a comma. Note that both indices will be included.

In [12]:
# single cell selection
# select the cell in row 5 and column rootrace
cell = example2.loc[3, 'project_start_date']
cell

u'7/8/2014'

In [13]:
# multiple cells selection
# option 1: use a python list to explicitly list the rows/columns
cell = example2.loc[[0, 2, 4], 'project_start_date']
cell

0    10/1/2013
2    8/20/2014
4    8/19/2014
Name: project_start_date, dtype: object

In [14]:
# option 2: use colon to indicate contiguous selection
cell = example2.loc[0:4, 'project_start_date']
cell

0    10/1/2013
1     1/1/2014
2    8/20/2014
3     7/8/2014
4    8/19/2014
Name: project_start_date, dtype: object

In [15]:
# if we want to select all columns, we can use a colon symbol :.
row5 = example2.loc[5, :]
row5

agency                                                             NIFA
project_title         DEVELOPMENT OF TOOLS TO ENABLE PLACE-BASED MAN...
fy_total_cost                                                       NaN
project_start_date                                            5/30/2014
project_end_date                                              9/30/2018
Name: 5, dtype: object

### Subsetting Data
#### Subsetting numerical data
Similar to the `where` statement in sql, we can also select only data that meet certain condition. Depending on whether the data is numberical or string, we should choose to use different syntax for each situation. For example, if we would like to select columns that start from year 2015, we can use a larger than or equal to operator condition to subset.

In [16]:
# conditional subsetting: put the conditional statement within the square brackets 
# the conditional statement here is that we want the cost to be higher than or equal to 50.0000.
example3 = example2[example2['fy_total_cost'] >= 50000]
example3.head()

,agency,project_title,fy_total_cost,project_start_date,project_end_date
16,NIFA,HATCH ACT OF 1887 - NY,490142.0,6/15/2013,2/14/2014
17,NIFA,ANIMAL HEALTH AND DISEASE RESEARCH PROGRAM - OH,56954.0,1/1/2013,12/31/2013
18,NIFA,HATCH ACT OF 1887 (MULTISTATE RESEARCH FUND) - NY,765728.0,7/1/2013,2/28/2014
19,NIFA,AGRABILITY OF UTAH,180000.0,2/15/2014,2/14/2016
20,NIFA,SGU RESTORING THE BUFFALO ECONOMY EDUCATION PR...,107468.0,3/1/2014,2/28/2017

#### Subsetting string/categorical data
When the column contains string data or categorical data, the comparison operators might not be the choice for data selection. Instead, we can compare each data in a column to a target list to see if the data in column is included in the list. This is done by calling the `isin` method.

In [17]:
# select specific agencies
# we specify the target list within the parentheses of the `isin` method
example4 = example2[example2['agency'].isin(['NIFA', 'ARS'])]
example4.head()

,agency,project_title,fy_total_cost,project_start_date,project_end_date
0,ARS,IMPROVE NUTRITION FOR HONEY BEE COLONIES TO ST...,NaN,10/1/2013,2/6/2014
1,ARS,ALGAL-BASED WATER TREATMENT TECHNOLOGIES FOR S...,NaN,1/1/2014,12/31/2018
2,NIFA,BIOLOGICAL CONTROL OF PIERCE'S DISEASE OF GRAP...,NaN,8/20/2014,9/30/2014
3,NIFA,MOLECULAR MECHSNISMS OF INTESTINAL METAL ION T...,NaN,7/8/2014,7/9/2014
4,NIFA,ASSESSING CLIMATE INFORMATION NEEDS AND OPPORT...,NaN,8/19/2014,8/20/2014

#### Subsetting with multiple conditions
If we want to subset the data with more than one condition, we can specify all the conditions and concatenate them with the python keyword `&`. Remember to put every single condition within a pair of parentheses.

In [18]:
# combine both selections from above
example5 = example2[(example2['fy_total_cost'] >= 50000) &
                        (example2['agency'].isin(['NIFA', 'ARS']))]
example5.head()

,agency,project_title,fy_total_cost,project_start_date,project_end_date
16,NIFA,HATCH ACT OF 1887 - NY,490142.0,6/15/2013,2/14/2014
17,NIFA,ANIMAL HEALTH AND DISEASE RESEARCH PROGRAM - OH,56954.0,1/1/2013,12/31/2013
18,NIFA,HATCH ACT OF 1887 (MULTISTATE RESEARCH FUND) - NY,765728.0,7/1/2013,2/28/2014
19,NIFA,AGRABILITY OF UTAH,180000.0,2/15/2014,2/14/2016
20,NIFA,SGU RESTORING THE BUFFALO ECONOMY EDUCATION PR...,107468.0,3/1/2014,2/28/2017

### Statistics
#### Descriptive stats
Pandas has integrated some very useful tools to help us understand the distribution of the data. The `describe` method computes the most commonly used descriptive statistics, such as count, mean, standard deviation and quantiles for a dataframe.

In [19]:
# see the descriptive statistics of the wage column
example.describe()

          project_id  congressional_district      fy  fy_total_cost
count    3192.000000             1360.000000  3192.0   1.005000e+03
mean   698709.102130                5.024265  2014.0   6.858399e+05
std     31939.102729                8.888327     0.0   1.077847e+06
min    589214.000000                0.000000  2014.0   2.363000e+03
25%    688547.500000                1.000000  2014.0   1.000000e+05
50%    689477.500000                3.000000  2014.0   2.499830e+05
75%    690275.250000                5.000000  2014.0   7.680000e+05
max    813655.000000               98.000000  2014.0   7.759400e+06

#### Value counts and unique values
For categorical values, it is often helpful to figure out what are the unique values of a given column, and the quantity of each data. Let's go back to the welfare data

In [20]:
# find out how many different agencies are there in the data
example['agency'].unique()

array([u'ARS', u'NIFA', u'FS'], dtype=object)

In [21]:
# to count how many observations for each agency appeared in the data
example['agency'].value_counts()

NIFA    2896
FS       184
ARS      112
Name: agency, dtype: int64

We know from the data dictionary that 0 represent not applicable, 1 represents white, not of hispanic origin, 2 represents black, not of hispanic origin, etc. So we can see from the data that most race information is not available in the welfare data.

### Adding and Updating Data
#### Creating columns
We sometimes need to creat a new column, either to save the previously calculation from other columns, or add new information to the dataframe. The syntax is given below:
`dataframe['column_name'] = value`
where:
dataframe is the dataframe in which the new column is created,
column_name is the string of the new column name, 
value is the value of the each cell.

In [22]:
# we can then calculate the monthly cost by dividing the project costs column by 12, 
# and assign this newly computed column to the monthly column
example5['monthly'] = example5['fy_total_cost']/12
example5.head()

,agency,project_title,fy_total_cost,project_start_date,project_end_date,monthly
16,NIFA,HATCH ACT OF 1887 - NY,490142.0,6/15/2013,2/14/2014,40845.166667
17,NIFA,ANIMAL HEALTH AND DISEASE RESEARCH PROGRAM - OH,56954.0,1/1/2013,12/31/2013,4746.166667
18,NIFA,HATCH ACT OF 1887 (MULTISTATE RESEARCH FUND) - NY,765728.0,7/1/2013,2/28/2014,63810.666667
19,NIFA,AGRABILITY OF UTAH,180000.0,2/15/2014,2/14/2016,15000.000000
20,NIFA,SGU RESTORING THE BUFFALO ECONOMY EDUCATION PR...,107468.0,3/1/2014,2/28/2017,8955.666667

### Grouping and Aggregating Data
#### Group by and aggregation functions
Like in SQL, it is also possible to group the dataframe by a column, and use aggregation function on them, and sort the result

In [23]:
# calculate the how many grats each agency funded
# step1: in the groupby method, we pass the column we want to group by, we can also select what columns
# we want to carry out the operation
# step2: use the count method to count the number of cases
# step3: sort the value in descending order (set the ascending parameter to False)
example.groupby('agency')['project_title'].count().sort_values(ascending=False)

agency
NIFA    2896
FS       184
ARS      112
Name: project_title, dtype: int64

Other useful aggregation functions are:
sum(): sum
mean(): average
agg(): use a python dictionary to specify aggregation function based on each column

### Merging Dataframes
Pandas provides an ability to merge (join) two datasets together, like you can do in SQL. You can store the results in a new dataframe.

In [24]:
merge_df = pd.merge(example2, example3, on=["project_title", "second var"], how="inner")
merge_df.head()

,agency_x,project_title,fy_total_cost_x,project_start_date_x,project_end_date_x,agency_y,fy_total_cost_y,project_start_date_y,project_end_date_y
0,NIFA,HATCH ACT OF 1887 - NY,490142.0,6/15/2013,2/14/2014,NIFA,490142.0,6/15/2013,2/14/2014
1,NIFA,HATCH ACT OF 1887 - NY,490142.0,6/15/2013,2/14/2014,NIFA,4411279.0,9/1/2013,8/31/2016
2,NIFA,HATCH ACT OF 1887 - NY,4411279.0,9/1/2013,8/31/2016,NIFA,490142.0,6/15/2013,2/14/2014
3,NIFA,HATCH ACT OF 1887 - NY,4411279.0,9/1/2013,8/31/2016,NIFA,4411279.0,9/1/2013,8/31/2016
4,NIFA,ANIMAL HEALTH AND DISEASE RESEARCH PROGRAM - OH,56954.0,1/1/2013,12/31/2013,NIFA,56954.0,1/1/2013,12/31/2013

In [25]:
merge_df.shape

(999, 9)

### Saving a CSV
You can save a copy of your dataframe as a .csv file.

In [30]:
example.to_csv("~/example_data.csv", encoding='utf8')